#!/bin/bash

case "$1" in

  start)
    echo "Switching off LEDs..." 
    echo 0 > /sys/class/leds/blue:ph21:led1/brightness
    echo 0 > /sys/class/leds/white:ph11:led3/brightness
    echo 0 > /sys/class/leds/green:ph07:led4/brightness
    echo 0 > /sys/class/leds/orange:ph20:led2/brightness
    ;;

  stop)
    echo "Switching on LEDs..." 
    echo 1 > /sys/class/leds/blue:ph21:led1/brightness    
    echo 1 > /sys/class/leds/white:ph11:led3/brightness
    echo 1 > /sys/class/leds/green:ph07:led4/brightness
    echo 1 > /sys/class/leds/orange:ph20:led2/brightness
    ;;

  *)
    echo "Usage: /etc/init.d/cuebie-leds {start|stop}"
    exit 1
    ;;

esac

